#!/usr/bin/env node
/**
 * Ovi English School - Main Orchestrator
 * Full automated pipeline: News → Script → Audio → Video → Publish
 */

const { spawn } = require('child_process');
const fs = require('fs').promises;
const path = require('path');
require('dotenv').config();

// Import modules
const { getNewsForEpisode } = require('./news-fetcher');
const { adaptNewsForLevel } = require('./content-adapter');
const { generateMetadata, saveMetadata } = require('./metadata-generator');
const { scanEpisodes, saveFeed } = require('./rss-generator');

// Configuration
const OUTPUT_DIR = path.join(__dirname, '..', 'output');
const LEVELS = ['beginner']; // Add 'intermediate', 'advanced' later

/**
 * Run Python script for audio generation
 * Uses file-based input for reliability
 */
function generateAudio(script, outputDir, level) {
  return new Promise(async (resolve, reject) => {
    // Save script to temp file (more reliable than stdin)
    const tempFile = path.join(outputDir, '.temp-script.txt');
    await fs.writeFile(tempFile, script);

    const pythonScript = path.join(__dirname, 'audio-generator.py');

    const proc = spawn('python3', [pythonScript, tempFile, outputDir, level], {
      stdio: 'inherit',
      env: { ...process.env, PYTHONUNBUFFERED: '1' }
    });

    proc.on('close', async (code) => {
      // Clean up temp file
      try { await fs.unlink(tempFile); } catch (e) {}
      code === 0 ? resolve() : reject(new Error(`Audio failed (code ${code})`));
    });
  });
}

/**
 * Convert audio to video for YouTube
 */
function convertToVideo(audioPath, outputPath) {
  return new Promise((resolve, reject) => {
    const pythonScript = path.join(__dirname, 'video-converter.py');

    const process = spawn('python3', [pythonScript, audioPath, '-o', outputPath], {
      stdio: 'inherit'
    });

    process.on('close', (code) => {
      code === 0 ? resolve(outputPath) : reject(new Error('Video conversion failed'));
    });
  });
}

/**
 * Upload to YouTube
 */
async function uploadToYouTube(videoPath, metadata) {
  const { uploadVideo } = require('./youtube-uploader');
  return uploadVideo(videoPath, {
    title: metadata.youtube.title,
    description: metadata.youtube.description,
    tags: metadata.youtube.tags,
    category: metadata.youtube.category,
    privacy: metadata.youtube.privacy
  });
}

/**
 * Save files
 */
async function saveScript(script, outputDir, level, date) {
  const filepath = path.join(outputDir, `ovi-english-${level}-${date}-script.txt`);
  await fs.writeFile(filepath, script);
  return filepath;
}

async function saveTranscript(script, story, outputDir, level, date) {
  const transcript = `# Ovi English School - Episode Transcript

**Date:** ${date}
**Level:** ${level.charAt(0).toUpperCase() + level.slice(1)}
**Topic:** ${story.title}

---

## Episode Script

${script}

---

## Source
- ${story.source}: ${story.title}
- Link: ${story.link || 'N/A'}

---
*Generated by Ovi English School*
`;
  const filepath = path.join(outputDir, `ovi-english-${level}-${date}-transcript.md`);
  await fs.writeFile(filepath, transcript);
  return filepath;
}

/**
 * Extract vocabulary from script
 */
function extractVocabulary(script) {
  const vocabSection = script.match(/vocabulary[:\s]*([\s\S]*?)(?:\n\n|\n#|$)/i);
  if (vocabSection) {
    const words = vocabSection[1].match(/["']([^"']+)["']/g) || [];
    return words.map(w => w.replace(/["']/g, '')).slice(0, 10);
  }
  return ['vocabulary', 'learning', 'news'];
}

/**
 * Main pipeline
 */
async function runPipeline(options = {}) {
  const {
    skipAudio = false,
    skipVideo = false,
    skipYouTube = false,
    skipRSS = false,
    language = 'english'
  } = options;

  console.log('\n' + '═'.repeat(50));
  console.log('🎓 OVI ENGLISH SCHOOL - Full Pipeline');
  console.log('═'.repeat(50));

  const date = new Date().toISOString().split('T')[0];
  const episodeDir = path.join(OUTPUT_DIR, date);
  await fs.mkdir(episodeDir, { recursive: true });

  const results = { date, episodeDir, files: [], urls: {} };

  // ━━━ STEP 1: Fetch News ━━━
  console.log('\n┌─ STEP 1: Fetch News');
  const stories = await getNewsForEpisode(language);
  const story = stories[0];
  console.log(`└─ ✅ Got story: ${story.title.slice(0, 50)}...`);

  for (const level of LEVELS) {
    console.log(`\n┌─ STEP 2: Generate ${level} content`);

    // Generate script
    const script = await adaptNewsForLevel(story, level);
    await saveScript(script, episodeDir, level, date);
    await saveTranscript(script, story, episodeDir, level, date);
    console.log(`├─ ✅ Script & transcript saved`);

    // Generate metadata
    const vocabulary = extractVocabulary(script);
    const metadata = saveMetadata(episodeDir, {
      date,
      level,
      topic: story.title,
      vocabulary,
      newsSource: story.source
    });
    console.log(`└─ ✅ Metadata generated`);

    // ━━━ STEP 3: Audio ━━━
    if (!skipAudio) {
      console.log(`\n┌─ STEP 3: Generate audio (Qwen3-TTS)`);
      try {
        await generateAudio(script, episodeDir, level);
        console.log(`└─ ✅ Audio generated`);
      } catch (e) {
        console.log(`└─ ⚠️  Audio failed: ${e.message}`);
      }
    }

    // ━━━ STEP 4: Video ━━━
    const audioPath = path.join(episodeDir, `ovi-english-${level}-${date}.mp3`);
    const videoPath = path.join(episodeDir, `ovi-english-${level}-${date}.mp4`);

    if (!skipVideo && !skipAudio) {
      console.log(`\n┌─ STEP 4: Convert to video`);
      try {
        await convertToVideo(audioPath, videoPath);
        console.log(`└─ ✅ Video created`);
        results.files.push(videoPath);
      } catch (e) {
        console.log(`└─ ⚠️  Video failed: ${e.message}`);
      }
    }

    // ━━━ STEP 5: YouTube Upload ━━━
    if (!skipYouTube && !skipVideo && !skipAudio) {
      console.log(`\n┌─ STEP 5: Upload to YouTube`);
      try {
        const ytResult = await uploadToYouTube(videoPath, metadata);
        if (ytResult.success) {
          console.log(`└─ ✅ YouTube: ${ytResult.url}`);
          results.urls.youtube = ytResult.url;
          await fs.writeFile(path.join(episodeDir, 'youtube-url.txt'), ytResult.url);
        }
      } catch (e) {
        console.log(`└─ ⚠️  YouTube failed: ${e.message}`);
      }
    }
  }

  // ━━━ STEP 6: Update RSS Feed ━━━
  if (!skipRSS) {
    console.log(`\n┌─ STEP 6: Update RSS feed`);
    const episodes = scanEpisodes(OUTPUT_DIR);
    const feedPath = path.join(__dirname, '..', 'feed.xml');
    saveFeed(feedPath, episodes);
    console.log(`└─ ✅ RSS feed updated (${episodes.length} episodes)`);
  }

  // ━━━ Summary ━━━
  console.log('\n' + '═'.repeat(50));
  console.log('✅ PIPELINE COMPLETE');
  console.log('═'.repeat(50));
  console.log(`📂 Output: ${episodeDir}`);
  if (results.urls.youtube) console.log(`🎬 YouTube: ${results.urls.youtube}`);
  console.log('📡 RSS: feed.xml ready for Spotify/Apple\n');

  return results;
}

/**
 * CLI
 */
async function main() {
  const args = process.argv.slice(2);

  if (args.includes('--help')) {
    console.log(`
Ovi English School - Full Automated Pipeline

Usage:
  npm start                  Run full pipeline
  npm start -- --skip-youtube   Skip YouTube upload
  npm start -- --skip-video     Skip video conversion
  npm start -- --skip-audio     Skip audio generation
  npm start -- --content-only   Only generate content (no audio/video)

Pipeline Steps:
  1. Fetch news from RSS feeds
  2. Generate educational script (Gemini AI)
  3. Create audio (Qwen3-TTS)
  4. Convert to video (FFmpeg)
  5. Upload to YouTube
  6. Update RSS feed for Spotify/Apple
`);
    return;
  }

  const options = {
    skipAudio: args.includes('--skip-audio') || args.includes('--content-only'),
    skipVideo: args.includes('--skip-video') || args.includes('--content-only'),
    skipYouTube: args.includes('--skip-youtube') || args.includes('--content-only'),
    skipRSS: args.includes('--skip-rss')
  };

  try {
    await runPipeline(options);
  } catch (error) {
    console.error('\n❌ Pipeline failed:', error.message);
    process.exit(1);
  }
}

module.exports = { runPipeline };

if (require.main === module) {
  main();
}
